# Generated by Django 3.0.7 on 2020-12-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='quizzes',
            field=models.ManyToManyField(related_name='topics', to='quiz.Quiz'),
        ),
    ]
